name: Deploy To PRD

run-name: "#${{ github.run_number }}. Deploy to PRD ran on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Workflow can be manually triggered
  workflow_dispatch:

  workflow_call:
    
jobs:

  derive-tag:
    uses: ./.github/workflows/derive-tag.yml
          
  deploy-to-prd:
    name: Deploy to PRD
    runs-on: ubuntu-latest
    needs: [derive-tag]
    environment: prd
    steps:

      - name: Grab Image Tag
        env:
          docker-tag: ${{ needs.derive-tag.outputs.docker-tag }}
        run: |
          echo "determining the image tag based off whatever versioning logic used"
          echo "tag equals: ${{ env.docker-tag }}"
          
      - name: Deploy to PRD
        run: echo "deploying via helm"
