name: Deploy To Dev

run-name: "#${{ github.run_number }}. Deploy to Dev ran on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Workflow can be manually triggered
  workflow_dispatch:
    inputs:
      image-tag:
      description: 'Specify the Image Tag to deploy:'
      required: true

  workflow_call:
    inputs:
      image-tag:
      description: 'The image tag'
      required: true
    
jobs:

  #derive-tag:
  #  uses: ./.github/workflows/derive-tag.yml  
          
  deploy-to-de:
    name: Deploy
    runs-on: ubuntu-latest
    #needs: [derive-tag]
    environment: dev
    steps:
    
  
      - name: Grab Image Tag
        run: echo ${{ inputs.image-tag}}
        #env:
        #  docker-tag: ${{ needs.derive-tag.outputs.docker-tag }}
        #run: |
        #  echo "determining the image tag based off whatever versioning logic used"
        #  echo "tag equals: ${{ env.docker-tag }}"
          
      - name: Deploy to Dev
        run: echo "deploying via helm"
