name: Deploy To Test

run-name: "#${{ github.run_number }}. Deploy to Test ran on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Workflow can be manually triggered
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Specify the Image Tag to deploy:'
        required: true
        type: string

  # or called upon by other workflows
  workflow_call:
    inputs:
      image-tag:
        description: 'The image tag'
        required: true
        type: string
    
jobs:
          
  deploy-to-dev:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Grab Image Tag
        # This is now injected as an input to the workflow
        run: echo ${{ inputs.image-tag }}
          
      - name: Deploy to Test
        run: echo "deploying via helm"
