name: Release Workflow

run-name: "#${{ github.run_number }}. Release Workflow ran on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Workflow can be manually triggered
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yml

  code-scan:
    uses: ./.github/workflows/code-scan.yml

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    needs: [build]
  
  publish-image:
    uses: ./.github/workflows/publish.yml
    needs: [unit-test]

  deploy-to-dev:
    uses: ./.github/workflows/deploy-to-dev.yml
    needs: [publish-image]

  deploy-to-test:
    uses: ./.github/workflows/deploy-to-test.yml
    needs: deploy-to-dev

  deploy-to-uat:
    uses: ./.github/workflows/deploy-to-uat.yml
    needs: deploy-to-test
          
  deploy-to-prd:
    name: Deploy to PRD
    uses: ./.github/workflows/deploy-to-prd.yml
    needs: deploy-to-uat
    
