name: Unit Test

run-name:  "#${{ github.run_number }}. Run Unit Tests on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Allow for manual execution and to trigger Secondary region deployments
  workflow_dispatch:

  workflow_call:
        
  # Auto trigger when pushes to selected branch naming conventions occur
  push: 
    branches: [main, release/**]
    paths-ignore: ['*.md']
  # Auto trigger when a release is created
  release:
    types: [published]

jobs:

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "running docker build --target=test"
